apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  namespace: ai-workspace
  name: workspace-phi-3-mini
resource:
  labelSelector:
    matchLabels:
      apps: llm-inference
  preferredNodes:
  -  moc-lau2px0t0lu
inference:
  preset:
    name: "phi-3-mini-4k-instruct"
