apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
 name: workspace-falcon-7b
 namespace: ai-workspace
resource:
 labelSelector:
   matchLabels:
     app: llm-inference
inference:
 preset:
   name: "falcon-7b-instruct"
