apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-phi-3-mini
resource:
  labelSelector:
    matchLabels:
      apps: llm-inference
  preferredNodes:
  -  moc-lmf0eqwuz6v
inference:
  preset:
    name: "phi-3-mini-4k-instruct"
