apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
 name: workspace-mistral-7b
 namespace: ai-workspace
resource:
 instanceType: "Standard_NC16_A2"
 labelSelector:
   matchLabels:
     app: llm-inference
inference:
 preset:
   name: "mistral-7b-instruct"
